"""Download Natural Earth 110m land geojson (public domain), sample evenly-spaced
points along each coastline ring, and emit a JS file with a flat (lat, lon) array.

Run:    python tools/build_globe_coastlines.py
Writes: assets/globe-coastlines.js
"""
import json
import math
import os
import sys
import urllib.request

URL = "https://raw.githubusercontent.com/nvkelso/natural-earth-vector/master/geojson/ne_110m_land.geojson"
TARGET_POINTS = 5000
HERE = os.path.dirname(__file__)
OUT = os.path.normpath(os.path.join(HERE, "..", "assets", "globe-coastlines.js"))


def fetch(url):
    req = urllib.request.Request(url, headers={
        "User-Agent": "DreamSoftwareSite-Build/1.0 (ryan@dreamsoftwaresolutions.com)",
    })
    with urllib.request.urlopen(req, timeout=60) as r:
        return r.read()


def rings_from_geojson(gj):
    """Yield each outer/inner ring as a list of [lon, lat]."""
    for feat in gj["features"]:
        g = feat["geometry"]
        if g["type"] == "Polygon":
            for ring in g["coordinates"]:
                yield ring
        elif g["type"] == "MultiPolygon":
            for poly in g["coordinates"]:
                for ring in poly:
                    yield ring


def ring_length(ring):
    """Total length of a ring in degrees of lat/lon (planar — good enough for sampling)."""
    s = 0.0
    for i in range(1, len(ring)):
        a, b = ring[i - 1], ring[i]
        dx = b[0] - a[0]
        dy = b[1] - a[1]
        s += math.sqrt(dx * dx + dy * dy)
    return s


def sample_ring(ring, spacing):
    """Walk along the ring, emit points every `spacing` degrees of path length."""
    out = []
    if len(ring) < 2:
        return out
    acc = 0.0
    out.append(ring[0])
    i = 1
    seg_a = ring[0]
    seg_b = ring[1]
    dx = seg_b[0] - seg_a[0]
    dy = seg_b[1] - seg_a[1]
    seg_len = math.sqrt(dx * dx + dy * dy)
    while i < len(ring):
        if acc + seg_len >= spacing and seg_len > 1e-9:
            remaining = spacing - acc
            t = remaining / seg_len
            nx = seg_a[0] + dx * t
            ny = seg_a[1] + dy * t
            out.append([nx, ny])
            seg_a = [nx, ny]
            dx = seg_b[0] - seg_a[0]
            dy = seg_b[1] - seg_a[1]
            seg_len = math.sqrt(dx * dx + dy * dy)
            acc = 0.0
        else:
            acc += seg_len
            i += 1
            if i >= len(ring):
                break
            seg_a = seg_b
            seg_b = ring[i]
            dx = seg_b[0] - seg_a[0]
            dy = seg_b[1] - seg_a[1]
            seg_len = math.sqrt(dx * dx + dy * dy)
    return out


def main():
    sys.stderr.write(f"fetching {URL} ...\n")
    raw = fetch(URL)
    gj = json.loads(raw)
    rings = list(rings_from_geojson(gj))
    total_len = sum(ring_length(r) for r in rings)
    sys.stderr.write(f"{len(rings)} rings, total path length {total_len:.1f} degrees\n")

    spacing = total_len / max(1, TARGET_POINTS)
    sys.stderr.write(f"spacing = {spacing:.3f} degrees\n")

    points = []  # list of (lat, lon) floats
    for ring in rings:
        # Skip trivially small rings (tiny islands add clutter)
        if ring_length(ring) < spacing * 1.2:
            continue
        for pt in sample_ring(ring, spacing):
            lon, lat = pt  # geojson is [lon, lat]
            points.append((round(lat, 2), round(lon, 2)))

    pre_thin = len(points)

    # Latitude-weighted thinning: polar coastlines (Antarctica, Arctic Canada/Russia/
    # Greenland) have enormously long perimeters that hog too many sample slots relative
    # to their visual importance on the globe. Thin them out so mid-latitude continents
    # get a fair share of the particle budget.
    import random
    random.seed(42)
    thinned = []
    for lat, lon in points:
        alat = abs(lat)
        if alat > 72:
            if random.random() < 0.28: thinned.append((lat, lon))  # keep ~28%
        elif alat > 58:
            if random.random() < 0.50: thinned.append((lat, lon))  # keep ~50%
        else:
            thinned.append((lat, lon))
    points = thinned

    sys.stderr.write(f"sampled {pre_thin}, thinned to {len(points)} (polar reduction)\n")

    # Flat array for compact output: [lat0, lon0, lat1, lon1, ...]
    flat = []
    for lat, lon in points:
        flat.append(lat)
        flat.append(lon)

    os.makedirs(os.path.dirname(OUT), exist_ok=True)
    with open(OUT, "w", encoding="utf-8") as f:
        f.write("// Natural Earth 110m land coastlines (public domain).\n")
        f.write("// GENERATED by tools/build_globe_coastlines.py — do not edit by hand.\n")
        f.write(f"// {len(points)} sample points, flat [lat, lon] pairs.\n")
        f.write("const GLOBE_COASTLINES = [")
        f.write(",".join(str(v) for v in flat))
        f.write("];\n")
    sys.stderr.write(f"wrote {OUT}\n")


if __name__ == "__main__":
    main()
